# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Marcus Messer
email: marcus.messer@kcl.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
Marcus Messer is a PhD student in the Department of Informatics. He obtained his MSci in Computer Science from Royal Holloway, University of London.

Marcus’ research focuses on the application of machine learning, particularly natural language processing, to automate the grading and feedback of code quality within student assignments.

Outside of his research, Marcus is a Graduate Teaching Assistant at King’s College London, teaching various courses across all years of the undergraduate and postgraduate curriculum.

Prior to his PhD, Marcus worked as a full-stack software engineer within a data analytics company and was responsible for various projects, including data ingestion, and web-based data visualization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marcusm.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  m-messer

# Build settings
plugins:
  - remote-theme
  - jekyll-feed

remote_theme: pages-themes/minimal@v0.2.0
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
